// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Products         string
	PVZ              string
	Receptions       string
	SchemaMigrations string
	Users            string
}{
	Products:         "products",
	PVZ:              "pvz",
	Receptions:       "receptions",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
