// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPVZS(t *testing.T) {
	t.Parallel()

	query := PVZS()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPVZSDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PVZS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPVZSQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := PVZS().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PVZS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPVZSSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PVZSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PVZS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPVZSExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PVZExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if PVZ exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PVZExists to return true, but got false.")
	}
}

func testPVZSFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	pvzFound, err := FindPVZ(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if pvzFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPVZSBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = PVZS().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPVZSOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := PVZS().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPVZSAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	pvzOne := &PVZ{}
	pvzTwo := &PVZ{}
	if err = randomize.Struct(seed, pvzOne, pvzDBTypes, false, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}
	if err = randomize.Struct(seed, pvzTwo, pvzDBTypes, false, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = pvzOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = pvzTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PVZS().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPVZSCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	pvzOne := &PVZ{}
	pvzTwo := &PVZ{}
	if err = randomize.Struct(seed, pvzOne, pvzDBTypes, false, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}
	if err = randomize.Struct(seed, pvzTwo, pvzDBTypes, false, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = pvzOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = pvzTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PVZS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func pvzBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *PVZ) error {
	*o = PVZ{}
	return nil
}

func pvzAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *PVZ) error {
	*o = PVZ{}
	return nil
}

func pvzAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *PVZ) error {
	*o = PVZ{}
	return nil
}

func pvzBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PVZ) error {
	*o = PVZ{}
	return nil
}

func pvzAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PVZ) error {
	*o = PVZ{}
	return nil
}

func pvzBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PVZ) error {
	*o = PVZ{}
	return nil
}

func pvzAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PVZ) error {
	*o = PVZ{}
	return nil
}

func pvzBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PVZ) error {
	*o = PVZ{}
	return nil
}

func pvzAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PVZ) error {
	*o = PVZ{}
	return nil
}

func testPVZSHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &PVZ{}
	o := &PVZ{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, pvzDBTypes, false); err != nil {
		t.Errorf("Unable to randomize PVZ object: %s", err)
	}

	AddPVZHook(boil.BeforeInsertHook, pvzBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	pvzBeforeInsertHooks = []PVZHook{}

	AddPVZHook(boil.AfterInsertHook, pvzAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	pvzAfterInsertHooks = []PVZHook{}

	AddPVZHook(boil.AfterSelectHook, pvzAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	pvzAfterSelectHooks = []PVZHook{}

	AddPVZHook(boil.BeforeUpdateHook, pvzBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	pvzBeforeUpdateHooks = []PVZHook{}

	AddPVZHook(boil.AfterUpdateHook, pvzAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	pvzAfterUpdateHooks = []PVZHook{}

	AddPVZHook(boil.BeforeDeleteHook, pvzBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	pvzBeforeDeleteHooks = []PVZHook{}

	AddPVZHook(boil.AfterDeleteHook, pvzAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	pvzAfterDeleteHooks = []PVZHook{}

	AddPVZHook(boil.BeforeUpsertHook, pvzBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	pvzBeforeUpsertHooks = []PVZHook{}

	AddPVZHook(boil.AfterUpsertHook, pvzAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	pvzAfterUpsertHooks = []PVZHook{}
}

func testPVZSInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PVZS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPVZSInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(pvzPrimaryKeyColumns, pvzColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := PVZS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPVZToManyReceptions(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PVZ
	var b, c Reception

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, receptionDBTypes, false, receptionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, receptionDBTypes, false, receptionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.PVZID = a.ID
	c.PVZID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Receptions().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.PVZID == b.PVZID {
			bFound = true
		}
		if v.PVZID == c.PVZID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := PVZSlice{&a}
	if err = a.L.LoadReceptions(ctx, tx, false, (*[]*PVZ)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Receptions); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Receptions = nil
	if err = a.L.LoadReceptions(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Receptions); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testPVZToManyAddOpReceptions(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PVZ
	var b, c, d, e Reception

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, pvzDBTypes, false, strmangle.SetComplement(pvzPrimaryKeyColumns, pvzColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Reception{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, receptionDBTypes, false, strmangle.SetComplement(receptionPrimaryKeyColumns, receptionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Reception{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddReceptions(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.PVZID {
			t.Error("foreign key was wrong value", a.ID, first.PVZID)
		}
		if a.ID != second.PVZID {
			t.Error("foreign key was wrong value", a.ID, second.PVZID)
		}

		if first.R.PVZ != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.PVZ != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Receptions[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Receptions[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Receptions().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testPVZSReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPVZSReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PVZSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPVZSSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PVZS().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	pvzDBTypes = map[string]string{`ID`: `bigint`, `Name`: `character varying`, `City`: `character varying`, `CreatedAt`: `timestamp without time zone`}
	_          = bytes.MinRead
)

func testPVZSUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(pvzPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(pvzAllColumns) == len(pvzPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PVZS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPVZSSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(pvzAllColumns) == len(pvzPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PVZ{}
	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PVZS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, pvzDBTypes, true, pvzPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(pvzAllColumns, pvzPrimaryKeyColumns) {
		fields = pvzAllColumns
	} else {
		fields = strmangle.SetComplement(
			pvzAllColumns,
			pvzPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PVZSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPVZSUpsert(t *testing.T) {
	t.Parallel()

	if len(pvzAllColumns) == len(pvzPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := PVZ{}
	if err = randomize.Struct(seed, &o, pvzDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PVZ: %s", err)
	}

	count, err := PVZS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, pvzDBTypes, false, pvzPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PVZ struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PVZ: %s", err)
	}

	count, err = PVZS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
